import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:quickprism/core/assets/assets.dart';
import 'package:quickprism/core/styles/app_styles.dart';
import 'package:quickprism/presentation/widgets/form_fields/normal_text_field.dart';

class WidgetQuotationDetails extends StatefulWidget {
  const WidgetQuotationDetails({super.key});

  @override
  State<WidgetQuotationDetails> createState() => _WidgetQuotationDetailsState();
}

class _WidgetQuotationDetailsState extends State<WidgetQuotationDetails> {
  final TextEditingController _quotationNumberController =
      TextEditingController();
  final TextEditingController _subjectController = TextEditingController();
  final TextEditingController _dateOfQuotationController =
      TextEditingController();
  final TextEditingController _dateOfExpiryController = TextEditingController();
  final TextEditingController _customerNameController = TextEditingController();
  final TextEditingController _gstNumberController = TextEditingController();
  final TextEditingController _bill1Controller = TextEditingController();
  final TextEditingController _bill2Controller = TextEditingController();
  final TextEditingController _bill3Controller = TextEditingController();
  final TextEditingController _ship1Controller = TextEditingController();
  final TextEditingController _ship2Controller = TextEditingController();
  final TextEditingController _ship3Controller = TextEditingController();
  final TextEditingController _shipStateController = TextEditingController();
  final TextEditingController _placeOfSupplyStateController =
      TextEditingController();
  final TextEditingController _regionController = TextEditingController();
  final TextEditingController _sellerSignatureController =
      TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: SingleChildScrollView(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              "Quotation Number",
              style: AppStyles.inter500153D3A3A,
            ),
            5.verticalSpace,
            NormalTextField(
              isFilled: true,
              label: "Autogenerated Number",
              hintText: "Autogenerated Number",
              controller: _quotationNumberController,
              inputType: TextInputType.number,
              validator: (value) {
                if (value!.isEmpty) {
                  return "Autogenerated Number not filled";
                }
              },
            ),
            Text(
              "Subject ",
              style: AppStyles.inter500153D3A3A,
            ),
            5.verticalSpace,
            NormalTextField(
              isFilled: true,
              label: "Your Requirement of ____",
              hintText: "Your Requirement of ____",
              controller: _subjectController,
              inputType: TextInputType.emailAddress,
              validator: (value) {
                if (value!.isEmpty) {
                  return "Enter the subject";
                }
              },
            ),
            Text(
              "Date of Quotation",
              style: AppStyles.inter500153D3A3A,
            ),
            5.verticalSpace,
            NormalTextField(
              isFilled: true,
              enabled: false,
              onTap: () {
                DatePickerDialog(
                  firstDate: DateTime.utc(2023),
                  lastDate: DateTime.utc(2025),
                );
              },
              label: "DDMMYYYY",
              hintText: "DDMMYYYY",
              borderColor: Colors.transparent,
              controller: _dateOfQuotationController,
              validator: (value) {
                if (value!.isEmpty) {
                  return "Auto Date is not filled";
                }
              },
            ),
            Text(
              "Date of Expiration",
              style: AppStyles.inter500153D3A3A,
            ),
            5.verticalSpace,
            NormalTextField(
              isFilled: true,
              enabled: false,
              onTap: () {
                DatePickerDialog(
                  firstDate: DateTime.utc(2023),
                  lastDate: DateTime.utc(2025),
                );
              },
              label: "DDMMYYYY",
              hintText: "DDMMYYYY",
              borderColor: Colors.transparent,
              controller: _dateOfExpiryController,
              suffix: Padding(
                padding: EdgeInsets.all(10.h),
                child: Image.asset(AppAssets.imageCaledarToday,height: 12.h,width: 12.w,fit: BoxFit.fill,),
              ),
              validator: (value) {
                if (value!.isEmpty) {
                  return "Auto Date is not filled";
                }
              },
            ),
            Text(
              "Customer Name / Company",
              style: AppStyles.inter500153D3A3A,
            ),
            5.verticalSpace,
            NormalTextField(
              isFilled: true,
              label: "Requisition Sender’s Name",
              hintText: "Requisition Sender’s Name",
              controller: _customerNameController,
              inputType: TextInputType.name,
              validator: (value) {
                if (value!.isEmpty) {
                  return "Enter Requisition Sender’s Name";
                }
              },
            ),
            Text(
              "Customer GST number",
              style: AppStyles.inter500153D3A3A,
            ),
            5.verticalSpace,
            NormalTextField(
              isFilled: true,
              label: "Enter Customer GST Number",
              hintText: "Enter Customer GST Number",
              controller: _gstNumberController,
              inputType: TextInputType.number,
              validator: (value) {
                if (value!.isEmpty) {
                  return "Enter Requisition Sender’s Name";
                }
              },
            ),
            Text(
              "Bill To",
              style: AppStyles.inter500153D3A3A,
            ),
            5.verticalSpace,
            NormalTextField(
              isFilled: true,
              label: "Prefilled",
              hintText: "Prefilled",
              controller: _bill1Controller,
              inputType: TextInputType.number,
              validator: (value) {
                if (value!.isEmpty) {
                  return "Enter Requisition Sender’s Name";
                }
              },
            ),
            NormalTextField(
              isFilled: true,
              label: "Enter Customer GST Number",
              hintText: "Enter Customer GST Number",
              controller: _gstNumberController,
              inputType: TextInputType.number,
              validator: (value) {
                if (value!.isEmpty) {
                  return "Enter Requisition Sender’s Name";
                }
              },
            ),
            NormalTextField(
              isFilled: true,
              label: "Enter Customer GST Number",
              hintText: "Enter Customer GST Number",
              controller: _gstNumberController,
              inputType: TextInputType.number,
              validator: (value) {
                if (value!.isEmpty) {
                  return "Enter Requisition Sender’s Name";
                }
              },
            ),
          ],
        ),
      ),
    );
  }
}
