name: quickprism
description: QP mobile application
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.19

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  injectable: ^2.3.2
  get_it: ^7.6.4
  auto_route: ^7.8.4
  flutter_screenutil: ^5.9.0
  cherry_toast: ^1.6.4
  dartz: ^0.10.1
  auto_route_generator: ^7.3.2
  google_fonts: ^6.1.0
  otp_text_field: ^1.1.3
  dio: ^5.3.3
  json_serializable: ^6.7.1
  email_validator: ^2.1.17
  cool_dropdown: ^2.1.0
  shimmer: ^3.0.0
  chuck_interceptor: ^2.0.7
  shared_preferences: ^2.2.2
  autocomplete_textfield: ^2.0.1
  flutter_advanced_switch: ^3.0.1
  flutter_typeahead: ^5.0.1
  flutter_svg: ^2.0.9
  table_calendar:
  intl:
  animate_do:
  pretty_dio_logger:
  flutter_staggered_grid_view: ^0.7.0
  glass: ^1.0.2+1
  marquee: ^2.2.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
