const placeHolderImage = "assets/images/placeholder.png";
const emptyImage = "assets/images/empty-box.png";
const errorImage = "assets/images/error-message.png";
// const List<String> itemUnitConstantsList = [
//   "pcs",
//   "kg",
//   "BAG-BAGS",
//   "BAL-BALE",
//   "BDL-BUNDLES",
//   "BOU-BILLION OF UNITS",
//   "BOX-BOX",
//   "CARTON"
// ];
final List<String> itemUnitConstantsList = [
  "BAGS",
  "BALE",
  "BUNDLES",
  "BUCKLES",
  "BILLIONS OF UNITS",
  "BOX",
  "BOTTLES",
  "BUNCHES",
  "CANS",
  "CUBIC METER",
  "CUBIC CENTIMETER",
  "CENTIMETER",
  "CARTONS",
  "DOZEN",
  "DRUM",
  "GREAT GROSS",
  "GRAMS",
  "GROSS",
  "GROSS YARDS",
  "KILOGRAMS",
  "KILOLITER",
  "KILOMETRE",
  "MILLILITER",
  "METERS",
  "METRIC TONS",
  "NUMBERS",
  "PACKS",
  "PIECES",
  "PAIRS",
  "QUINTAL",
  "ROLLS",
  "SETS",
  "SQUARE FEET",
  "SQUARE METERS",
  "SQUARE YARDS",
  "TABLETS",
  "TEN GROSS",
  "THOUSANDS",
  "TONNES",
  "TUBES",
  "US GALLONS",
  "UNITS",
  "YARDS",
  "OTHERS",
];
